version: '2'
services:
  pre-auth-doc:
    build: .
    image: registry.wosai-inc.com/pre-auth-doc
    restart: always
    container_name: pre-auth-doc
    ports:
      - "11150:4000"
    network_mode: bridge
    volumes:
      - /usr/share/pre-auth-doc:/gitbook/_book