version: '2'
services:
  e-invoice-doc:
    build: .
    image: registry.wosai-inc.com/pre-auth-doc
    restart: always
    container_name: pre-auth-doc
    ports:
      - "11140:4000"
    volumes:
      - /usr/share/pre-auth-doc:/gitbook/_book